openapi: 3.2.0
info:
  title: Audiences Eventtrackers API
  description: The Audience API helps LiveIntent partners to programmatically exchange data for creating and managing audiences. The API enables a high level of automation, which helps LiveIntent partners increase efficiency, reduce labor requirements, and improve audience delivery time. As a LiveIntent partner, you can leverage the Audience API to create and manage Custom Audience. This API supports the HTTP GET, POST, and PATCH methods. The following sections describe how to call the endpoints.
  version: 1.0.0
servers:
- url: https://audiences-staging.bln.liveintent.com
  description: 'staging


    '
- url: https://audiences.liveintent.com
  description: 'production


    '
security:
- Bearer: []
tags:
- name: Eventtrackers
paths:
  /eventtrackers:
    description: 'Create a new event tracker audience.


      '
    post:
      description: Create a new event tracker audience.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAudiencePayload'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAudienceResponse'
        '400':
          description: 'Invalid request parameters.


            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
                description: 'Invalid request parameters.


                  '
        '401':
          description: 'Authentication credentials were missing or incorrect.


            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
                description: 'Authentication credentials were missing or incorrect.


                  '
        '500':
          description: 'Failed to create event tracker audience.


            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationError'
                description: 'Failed to create event tracker audience.


                  '
      tags:
      - Eventtrackers
      summary: Create eventtrackers
      x-summary-source: derived
      operationId: postEventtrackers
      x-operation-id-source: derived
components:
  schemas:
    AttributionWindow:
      type: object
      properties:
        pcc:
          type: integer
          format: int64
        pvc:
          type: integer
          format: int64
      required:
      - pcc
      - pvc
    Json:
      oneOf:
      - type: object
        properties:
          Arr:
            $ref: '#/components/schemas/Arr'
        additionalProperties: false
        required:
        - Arr
      - type: object
        properties:
          'Null':
            $ref: '#/components/schemas/Null'
        additionalProperties: false
        required:
        - 'Null'
      - type: object
        properties:
          Bool:
            $ref: '#/components/schemas/Bool'
        additionalProperties: false
        required:
        - Bool
      - type: object
        properties:
          Num:
            $ref: '#/components/schemas/Num'
        additionalProperties: false
        required:
        - Num
      - type: object
        properties:
          Str:
            $ref: '#/components/schemas/Str'
        additionalProperties: false
        required:
        - Str
      - type: object
        properties:
          Obj:
            $ref: '#/components/schemas/Obj'
        additionalProperties: false
        required:
        - Obj
    'Null':
      type: object
      properties: {}
    Num:
      type: object
      properties:
        value:
          type: number
          format: double
      required:
      - value
    AudienceWithMetadataDTO:
      type: object
      properties:
        deletesAt:
          type:
          - string
          - 'null'
          format: date-time
        deletedAt:
          type:
          - string
          - 'null'
          format: date-time
        externalAudienceId:
          type:
          - string
          - 'null'
        iabCategory:
          type:
          - string
          - 'null'
        archivesAt:
          type:
          - string
          - 'null'
          format: date-time
        accountId:
          type: integer
          format: int64
        dataProviderId:
          type: integer
          format: int32
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        metadata:
          type: object
          properties: {}
          additionalProperties:
            $ref: '#/components/schemas/AudienceMetadataDTO'
        dataProviderPrefix:
          type: string
        additionalAttributes:
          anyOf:
          - type: 'null'
          - $ref: '#/components/schemas/DynamicAudienceAttributesDTO'
        name:
          type: string
        updatedAt:
          type: string
          format: date-time
        internal:
          type: boolean
        replacementId:
          type:
          - integer
          - 'null'
          format: int64
        archived:
          type: boolean
        zetaTaxonomyNodeId:
          type:
          - string
          - 'null'
        status:
          $ref: '#/components/schemas/SimpleAudienceStatus'
      required:
      - id
      - name
      - accountId
      - dataProviderId
      - dataProviderPrefix
      - createdAt
      - archived
      - status
      - internal
      - metadata
      - updatedAt
    SimpleAudienceStatus:
      type: string
      enum:
      - Active
      - Archived
      - Deleted
    Str:
      type: object
      properties:
        value:
          type: string
      required:
      - value
    CreateAudienceResponse:
      type: object
      properties:
        ruleId:
          type: integer
          format: int32
        audience:
          $ref: '#/components/schemas/AudienceWithMetadataDTO'
      required:
      - ruleId
      - audience
    AudienceMetadataDTO:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Json'
        updatedAt:
          type: string
          format: date-time
      required:
      - data
      - updatedAt
    Obj:
      type: object
      properties:
        fields:
          type: array
          items:
            allOf:
            - type: string
            - $ref: '#/components/schemas/Json'
      required:
      - fields
    Arr:
      type: object
      properties:
        elements:
          type: array
          items:
            $ref: '#/components/schemas/Json'
      required:
      - elements
    DynamicAudienceAttributesDTO:
      type: object
      properties:
        ruleId:
          type: integer
          format: int64
        ttl:
          type: integer
          format: int32
      required:
      - ruleId
      - ttl
    Bool:
      type: object
      properties:
        value:
          type: boolean
      required:
      - value
    CreateAudiencePayload:
      type: object
      properties:
        attributionWindow:
          $ref: '#/components/schemas/AttributionWindow'
        body:
          $ref: '#/components/schemas/Json'
        name:
          type: string
        appIds:
          type: array
          items:
            type: string
          minItems: 1
        pixelId:
          type: string
        accountId:
          type: integer
          format: int64
        audienceTtl:
          type: integer
          format: int32
        conversionId:
          type: integer
          format: int64
      required:
      - conversionId
      - pixelId
      - accountId
      - appIds
      - name
      - attributionWindow
      - audienceTtl
      - body
    ApplicationError:
      type: object
      properties:
        httpStatus:
          type: integer
          format: int32
        message:
          type: string
        errorCode:
          type: string
      required:
      - httpStatus
      - message
      - errorCode
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'For accessing internal endpoints an access token is required. It needs to be sent as a Bearer token in the _Authorization_ header.


        '
      name: Authorization
      in: header
